// Popular US and SGX stocks and ETFs
const stockList = {
  us: [
    { symbol: 'AAPL', name: 'Apple Inc.' },
    { symbol: 'MSFT', name: 'Microsoft Corp.' },
    { symbol: 'GOOGL', name: 'Alphabet Inc.' },
    { symbol: 'AMZN', name: 'Amazon.com Inc.' },
    { symbol: 'META', name: 'Meta Platforms' },
    { symbol: 'NVDA', name: 'NVIDIA Corp.' },
    { symbol: 'JPM', name: 'JPMorgan Chase' },
    { symbol: 'VZ', name: 'Verizon Communications' },
    { symbol: 'T', name: 'AT&T Inc.' },
    { symbol: 'KO', name: 'Coca-Cola Co.' },
    { symbol: 'PEP', name: 'PepsiCo Inc.' },
    { symbol: 'MCD', name: "McDonald's Corp." },
    { symbol: 'XOM', name: 'Exxon Mobil' },
    { symbol: 'CVX', name: 'Chevron Corp.' },
    { symbol: 'PG', name: 'Procter & Gamble' },
    { symbol: 'JNJ', name: 'Johnson & Johnson' },
    { symbol: 'HD', name: 'Home Depot' },
    { symbol: 'BAC', name: 'Bank of America' },
    { symbol: 'WFC', name: 'Wells Fargo' },
    { symbol: 'ABBV', name: 'AbbVie Inc.' },
    { symbol: 'PFE', name: 'Pfizer Inc.' },
    { symbol: 'MRK', name: 'Merck & Co.' },
    { symbol: 'DIS', name: 'Walt Disney Co.' },
    { symbol: 'NFLX', name: 'Netflix Inc.' },
    { symbol: 'TSLA', name: 'Tesla Inc.' },
    // ETFs
    { symbol: 'SPY', name: 'SPDR S&P 500 ETF' },
    { symbol: 'QQQ', name: 'Invesco QQQ Trust' },
    { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF' },
    { symbol: 'VOO', name: 'Vanguard S&P 500 ETF' },
    { symbol: 'BND', name: 'Vanguard Total Bond Market ETF' },
    { symbol: 'AGG', name: 'iShares Core U.S. Aggregate Bond ETF' },
    { symbol: 'GLD', name: 'SPDR Gold Trust' },
    { symbol: 'SLV', name: 'iShares Silver Trust' },
    { symbol: 'EEM', name: 'iShares MSCI Emerging Markets ETF' },
    { symbol: 'EFA', name: 'iShares MSCI EAFE ETF' },
    { symbol: 'IWM', name: 'iShares Russell 2000 ETF' },
    { symbol: 'XLK', name: 'Technology Select Sector SPDR Fund' },
    { symbol: 'XLF', name: 'Financial Select Sector SPDR Fund' },
    { symbol: 'XLE', name: 'Energy Select Sector SPDR Fund' },
    { symbol: 'XLV', name: 'Health Care Select Sector SPDR Fund' },
    { symbol: 'XLP', name: 'Consumer Staples Select Sector SPDR Fund' },
    { symbol: 'XLI', name: 'Industrial Select Sector SPDR Fund' },
    { symbol: 'XLY', name: 'Consumer Discretionary Select Sector SPDR Fund' },
    { symbol: 'XLU', name: 'Utilities Select Sector SPDR Fund' },
  ],
  sg: [
    { symbol: 'D05.SI', name: 'DBS Group Holdings' },
    { symbol: 'O39.SI', name: 'OCBC Bank' },
    { symbol: 'U11.SI', name: 'United Overseas Bank' },
    { symbol: 'C6L.SI', name: 'Singapore Airlines' },
    { symbol: 'Z74.SI', name: 'Singtel' },
    { symbol: 'BN4.SI', name: 'Keppel Corp' },
    { symbol: 'S63.SI', name: 'ST Engineering' },
    { symbol: 'C52.SI', name: 'ComfortDelGro' },
    { symbol: 'F34.SI', name: 'Wilmar International' },
    { symbol: 'G13.SI', name: 'Genting Singapore' },
    { symbol: 'H78.SI', name: 'Hongkong Land' },
    { symbol: 'J36.SI', name: 'Jardine Matheson' },
    { symbol: 'C07.SI', name: 'Jardine Cycle & Carriage' },
    { symbol: 'S68.SI', name: 'Singapore Exchange' },
    // ETFs
    { symbol: 'ES3.SI', name: 'SPDR Straits Times Index ETF' },
    { symbol: 'G3B.SI', name: 'Nikko AM Singapore STI ETF' },
    { symbol: 'CFA.SI', name: 'Nikko AM SGD Investment Grade Corp Bond ETF' },
    { symbol: 'O87.SI', name: 'Lion-OCBC Securities China Leaders ETF' },
    { symbol: 'M62.SI', name: 'Lion-OCBC Securities Singapore Dividend ETF' },
    { symbol: 'N6M.SI', name: 'United SSE 50 ETF' },
    { symbol: 'S27.SI', name: 'Singapore Bond ETF' },
    { symbol: 'ER7.SI', name: 'Lion-OCBC Securities APAC Dividend ETF' },
    { symbol: 'NS8U.SI', name: 'Nikko AM Asia ex-Japan REIT ETF' },
    { symbol: 'GRN.SI', name: 'UOBAM Green Bond ETF' },
  ]
};

module.exports = stockList;